on:
  push:
    branches:
      - main
    paths:
      - 'notification-system/**'
      - '.github/workflows/notification-system-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'notification-system/**'
      - '.github/workflows/notification-system-ci.yml' 

name: Notification System CI

jobs:
  build:
    name: Build and Test Notification System
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24.11.1

      - name: Install Dependencies
        run: |
          cd notification-system
          npm ci
          npx nx run-many -t build
          